-- ###############################################################
--  SCRIPT NAME: LOAD_BRONZE_STAGE_AND_DATA.sql
--  PROJECT: SNOWFLAKE DATA PIPELINE AND ANALYTICS PROJECT
--  DESCRIPTION:
--    THIS SCRIPT CREATES INTERNAL STAGES FOR CRM AND ERP DATA FILES,
--    AND LOADS RAW CSV DATA INTO THE BRONZE LAYER TABLES.
-- ###############################################################

--  WARNING:
-- THIS SCRIPT PERFORMS FULL DATA LOADS INTO BRONZE TABLES.
-- EXECUTION WILL OVERWRITE EXISTING STAGE FILES AND RELOAD RAW DATA.

-- ###############################################################
-- Step 1: CREATE OR REPLACE A FILE FORMAT FOR CSV FILES
-- ###############################################################
CREATE OR REPLACE FILE FORMAT DATA_DB.BRONZE.CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE
COMPRESSION = 'AUTO';

-- ###############################################################
--  STEP 2: CREATE OR REPLACE INTERNAL STAGES FOR SOURCE FILES
-- ###############################################################

CREATE OR REPLACE STAGE DATA_DB.BRONZE.CRM_STAGE
FILE_FORMAT = DATA_DB.BRONZE.CSV_FILE_FORMAT;

CREATE OR REPLACE STAGE DATA_DB.BRONZE.ERP_STAGE
FILE_FORMAT = DATA_DB.BRONZE.CSV_FILE_FORMAT;

-- ###############################################################
--  STEP 3: LOAD CSV FILES INTO BRONZE TABLES
-- ###############################################################

-- =========================
--  LOAD CRM SOURCE FILES
-- =========================

COPY INTO DATA_DB.BRONZE.CRM_CUST_INFO
FROM @DATA_DB.BRONZE.CRM_STAGE/CUST_INFO.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO DATA_DB.BRONZE.CRM_PRD_INFO
FROM @DATA_DB.BRONZE.CRM_STAGE/PRD_INFO.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO DATA_DB.BRONZE.CRM_SALES_DETAILS
FROM @DATA_DB.BRONZE.CRM_STAGE/SALES_DETAILS.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- =========================
--  LOAD ERP SOURCE FILES
-- =========================

COPY INTO DATA_DB.BRONZE.ERP_CUST_AZ12
FROM @DATA_DB.BRONZE.ERP_STAGE/CUST_AZ12.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO DATA_DB.BRONZE.ERP_LOC_A101
FROM @DATA_DB.BRONZE.ERP_STAGE/LOC_A101.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO DATA_DB.BRONZE.ERP_PX_CAT_G1V2
FROM @DATA_DB.BRONZE.ERP_STAGE/PX_CAT_G1V2.CSV
FILE_FORMAT = (FORMAT_NAME = DATA_DB.BRONZE.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- ###############################################################
--  END OF SCRIPT
-- ###############################################################
